<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\projectA.teamA\projectA.teamA.csproj" />
    <ProjectReference Include="..\projectA.teamB\projectA.teamB.csproj" />
  </ItemGroup>

</Project>
